// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuKrCQTHNPmIQz8eRoG_wa4wJCjtcwwas',
    appId: '1:246922721396:web:3e28f54dda214b0d297921',
    messagingSenderId: '246922721396',
    projectId: 'leaveapplication-8c052',
    authDomain: 'leaveapplication-8c052.firebaseapp.com',
    storageBucket: 'leaveapplication-8c052.firebasestorage.app',
    measurementId: 'G-L74ZPBL8CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vh0bc_uf_zTw0ZTHf5HRSGR6FnEMaPw',
    appId: '1:246922721396:android:6779637c3a6856fb297921',
    messagingSenderId: '246922721396',
    projectId: 'leaveapplication-8c052',
    storageBucket: 'leaveapplication-8c052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4gOa6iprPwpdix_08qAGebaNCx6V7WZg',
    appId: '1:246922721396:ios:d566af96cd8acaff297921',
    messagingSenderId: '246922721396',
    projectId: 'leaveapplication-8c052',
    storageBucket: 'leaveapplication-8c052.firebasestorage.app',
    iosBundleId: 'com.example.leaveApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4gOa6iprPwpdix_08qAGebaNCx6V7WZg',
    appId: '1:246922721396:ios:d566af96cd8acaff297921',
    messagingSenderId: '246922721396',
    projectId: 'leaveapplication-8c052',
    storageBucket: 'leaveapplication-8c052.firebasestorage.app',
    iosBundleId: 'com.example.leaveApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuKrCQTHNPmIQz8eRoG_wa4wJCjtcwwas',
    appId: '1:246922721396:web:7f1565896660d494297921',
    messagingSenderId: '246922721396',
    projectId: 'leaveapplication-8c052',
    authDomain: 'leaveapplication-8c052.firebaseapp.com',
    storageBucket: 'leaveapplication-8c052.firebasestorage.app',
    measurementId: 'G-WQVC6WM36E',
  );

}